apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sValidImages
metadata:
  name: deployment-must-have-valid-images
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces:
      - "default"
  parameters:
    repos:
      - "docker.repo.schwarz/"
